# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        name: Ruff isort
        args: [--fix, --select=I]
      - id: ruff-format
        name: Ruff format
