[project]
name = "qsimplify"
version = "0.1.0"
description = "A quantum circuit simplifier"
readme = "README.md"
authors = [
    { name = "Víctor Mardones", email = "vmardones.dev@gmail.com" }
]
requires-python = ">=3.12,<4"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "graphviz>=0.20.3",
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "pydantic>=2.11.3",
    "pylatexenc>=2.10",
    "qiskit>=2.0.0",
    "qiskit-aer>=0.17.1", # Only used by qft.py
    "qiskit-ibm-runtime>=0.40.0", # Only used by qft.py
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pyright>=1.1.398",
    "pysonar>=1.1.0.2035",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.4",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "ERA", # eradicate
    "ANN", # flake8-annotations
    "S", # flake8-bandit
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "C4", # flake8-comprehensions
    "FIX", # flake8-fixme
    "FA", # flake8-future-annotations
    "LOG", # flake8-logging
    "G", # flake8-logging-format
    "INP", # flake8-no-pep420
    "PIE", # flake8-pie
    "PT", # flake8-pytest-style
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SLF", # flake8-self
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "FLY", # flynt
    "C90", # mccabe
    "N", #  pep8-naming
    "PERF", # Perflint
    "E", # Error (pycodestyle)
    "DOC", # pydoclint
    "D", # pydocstyle
    "PLC", # Convention (Pylint)
    "PLE", # Error (Pylint)
    "FURB", # refurb
    "RUF" # Ruff-specific rules
]
ignore = [
    "D211", # blank-line-before-class
    "D213", # multi-line-summary-first-line
    "PLC0414" # useless-import-alias
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "ANN201", # missing-return-type-undocumented-public-function
    "S101" # assert
]

[tool.coverage.run]
omit = [
    "tests/**",
    "qsimplify/app.py",
    "qsimplify/demo.py",
    "qsimplify/qft.py",
    "qsimplify/qft2.py"
]
