sonar.projectKey=qsimplify
# Don't analyze generated HTML code coverage files
sonar.exclusions=coverage/**
# Exclude tests and entrypoints ("main" files) from coverage
sonar.coverage.exclusions=tests/**, qsimplify/app.py, qsimplify/demo.py, qsimplify/qft.py, qsimplify/qft2.py
# Exclude tests from duplicate code detection
sonar.cpd.exclusions=tests/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
