sonar.projectKey=qsimplify
sonar.exclusions=coverage/**
sonar.coverage.exclusions=tests/**, qsimplify/app.py, qsimplify/demo.py, qsimplify/qft.py, qsimplify/qft2.py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
